### ISSUE TITLE
Wrong format for 19

### ISSUE THREAD

**Issue by urinieto** [DDMAL/salami-data-public#11]
There is a version control conflict in this file: https://github.com/DDMAL/salami-data-public/blob/master/annotations/19/textfile2.txt

I assume that the new "Silence" row is correct. However, it should be fixed in order for the new JAMS parser (and most likely any parser) to work.

Thanks!

**Comment by grrrr** [comment]
I have submitted a respective pull request last March.
https://github.com/DDMAL/salami-data-public/pull/7 https://github.com/DDMAL/salami-data-public/pull/7
best, Thomas

**Comment by ahankinson** [comment]
I just merged the pull request. Should be good now.

**Comment by urinieto** [comment]
Awesome, thanks!
