### ISSUE TITLE
Duplicate annotations 

### ISSUE THREAD

**Issue by grrrr** [DDMAL/salami-data-public#6]
The annotations
1507/textfile1b.txt
275/textfile2b.txt
seem to be coarse duplicates of their counterparts 1507/textfile1.txt, and 275/textfile2.txt.

**Comment by jblsmith** [comment]
These are two exceptions; the hierarchical structure of sonatas is so well understood, that when these examples came up we were hard-pressed not to indicate the proper sonata structure: exposition, development, recap; the main and secondary theme beneath them; and the more atomic 'musical unit' level that is the general SALAMI lowercase standard beneath them. The important inconsistency might be that the order of the files is swapped; it would be nicer if the "b" files were the more-zoomed-out-than-expected view for both annotations. I'll make it so.
